### ISSUE TITLE
Setup failing :(

### ISSUE THREAD

**Issue by istern** [JakobChristensen/Sitecore.Pathfinder#51]
Just made a clone of repository, it builds fines and no errors in unit tests. but trying to scc help gives the following error

λ scc help
Failed to load assembly: Could not load file or assembly 'Sitecore.Pathfinder.HtmlFile, Version=0.6.7.28336, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515): C:\Program Files\SitecorePathfinder\Sitecore.Pathfinder.HtmlFile.dll
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Could not load type 'Sitecore.Pathfinder.Checking.CheckerBase' from assembly 'Sitecore.Pathfinder.Core, Version=0.7.0.37953, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Sitecore.Pathfinder.Checking.CheckerBase' from assembly 'Sitecore.Pathfinder.Core, Version=0.7.0.37953, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Sitecore.Pathfinder.Checking.CheckerBase' from assembly 'Sitecore.Pathfinder.Core, Version=0.7.0.37953, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Sitecore.Pathfinder.Checking.CheckerBase' from assembly 'Sitecore.Pathfinder.Core, Version=0.7.0.37953, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Sitecore.Pathfinder.Checking.CheckerBase' from assembly 'Sitecore.Pathfinder.Core, Version=0.7.0.37953, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Sitecore.Pathfinder.Checking.CheckerBase' from assembly 'Sitecore.Pathfinder.Core, Version=0.7.0.37953, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Sitecore.Pathfinder.Checking.CheckerBase' from assembly 'Sitecore.Pathfinder.Core, Version=0.7.0.37953, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Sitecore.Pathfinder.Checking.CheckerBase' from assembly 'Sitecore.Pathfinder.Core, Version=0.7.0.37953, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Sitecore.Pathfinder.Checking.CheckerBase' from assembly 'Sitecore.Pathfinder.Core, Version=0.7.0.37953, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Sitecore.Pathfinder.Checking.CheckerBase' from assembly 'Sitecore.Pathfinder.Core, Version=0.7.0.37953, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Sitecore.Pathfinder.Checking.CheckerBase' from assembly 'Sitecore.Pathfinder.Core, Version=0.7.0.37953, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Sitecore.Pathfinder.Checking.CheckerBase' from assembly 'Sitecore.Pathfinder.Core, Version=0.7.0.37953, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Sitecore.Pathfinder.Checking.CheckerBase' from assembly 'Sitecore.Pathfinder.Core, Version=0.7.0.37953, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Sitecore.Pathfinder.Checking.CheckerBase' from assembly 'Sitecore.Pathfinder.Core, Version=0.7.0.37953, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Sitecore.Pathfinder.Checking.CheckerBase' from assembly 'Sitecore.Pathfinder.Core, Version=0.7.0.37953, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Sitecore.Pathfinder.Checking.CheckerBase' from assembly 'Sitecore.Pathfinder.Core, Version=0.7.0.37953, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Sitecore.Pathfinder.Checking.CheckerBase' from assembly 'Sitecore.Pathfinder.Core, Version=0.7.0.37953, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Sitecore.Pathfinder.Checking.CheckerBase' from assembly 'Sitecore.Pathfinder.Core, Version=0.7.0.37953, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Sitecore.Pathfinder.Checking.CheckerBase' from assembly 'Sitecore.Pathfinder.Core, Version=0.7.0.37953, Culture=neutral, PublicKeyToken=null'.

Unhandled Exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.get_InnerCatalog()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.GetExports(ImportDefinition definition)
   at System.ComponentModel.Composition.Hosting.AggregateCatalog.GetExports(ImportDefinition definition)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InternalGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.AggregateExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.CompositionContainer.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValueCore[T](String contractName, ImportCardinality cardinality)
   at Sitecore.Pathfinder.Extensions.CompositionServiceExtensions.Resolve[T](ICompositionService compositionService) in C:\Projects\Sitecore.Pathfinder\src\Sitecore.Pathfinder.Core\Extensions\CompositionServiceExtensions.cs:line 32
   at Sitecore.Pathfinder.HostService.GetTaskRunner[T]() in C:\Projects\Sitecore.Pathfinder\src\Sitecore.Pathfinder.Core\HostService.cs:line 29
   at Sitecore.Pathfinder.Program.Main(String[] args) in C:\Projects\Sitecore.Pathfinder\src\Sitecore.Pathfinder.Console\Program.cs:line 18

**Comment by JakobChristensen** [comment]
:(

That is odd - there should be no Sitecore.Pathfinder.HtmlFile assembly - it was renamed to Sitecore.Pathfinder.Html in 0.7.0.

Do you have an older build in your path?

**Comment by istern** [comment]
Hi Jakob cleaned the folder and it worked, Initialy i had the 0.6 version installed, i replaced it with my own compiled 0.7 version and had the error, after i deleted all files and then copied in my 0.7 version again then it worked.
