### ISSUE TITLE
scc throws error, wants MarkdownSharp.dll

### ISSUE THREAD

**Issue by sitecorian** [JakobChristensen/Sitecore.Pathfinder#55]
Maybe it's something with my machine. I grabbed the latest .zip (v0.8.330), unpacked to `C:\Program Files (x86)\SitecorePathfinder` (removed prior files from there). Running `scc` throws the error. Copying MarkdownSharp.dll to `C:\Program Files (x86)\SitecorePathfinder\` fixes the issue.

`````` C:\Users\as\Source\Repos\pathfinder-sandbox>scc
scc.cmd(0,0): error SCC1007: C:\Program Files (x86)\SitecorePathfinder\MarkdownS
harp.dll
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at Sitecore.Pathfinder.IO.FileSystemService.GetVersion(String fileName)
   at Sitecore.Pathfinder.IO.FileSystemService.CopyIfNewer(String sourceFileName
, String targetFileName)
   at Sitecore.Pathfinder.Extensibility.ExtensionBase.CopyToolsFileToWebsiteBinD
irectory(IBuildContext context, String fileName)
   at Sitecore.Pathfinder.Markdown.MarkdownExtension.UpdateWebsiteFiles(IBuildCo
ntext context)
   at Sitecore.Pathfinder.Tasks.UpdateWebsiteFiles.UpdateExtensions(IBuildContex
t context)
   at Sitecore.Pathfinder.Tasks.UpdateWebsiteFiles.UpdateWebsite(IBuildContext c
ontext)
   at Sitecore.Pathfinder.Tasks.UpdateWebsiteFiles.Run(IBuildContext context)
   at Sitecore.Pathfinder.Tasks.Building.BuildTaskBase.Run(ITaskContext context)

   at Sitecore.Pathfinder.Tasks.TaskRunnerBase.RunTask(ITaskContext context, ITa
sk task, LifeCycle lifeCycle)
Project metrics: 1 items, 1 templates, 0 media files, 0 renderings, 0 files
Time: 440ms, Ducats earned: 0 ```
``````

**Comment by JakobChristensen** [comment]
Markdown no longer supported.
